server:
  port: 8082

keycloak:
  configurationFile: "classpath:keycloak.json"

opentracing:
  jaeger:
    enabled: true
    service-name: "providers"
    http-sender:
      url: "http://localhost:14268/api/traces"
    probabilistic-sampler:
      sampling-rate: 1